"""empty message

Revision ID: 87109efae90b
Revises: 77de3ae3d421
Create Date: 2023-03-20 07:32:14.431403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87109efae90b'
down_revision = '77de3ae3d421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('birth_year', sa.String(length=150), nullable=False),
    sa.Column('eye_color', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=150), nullable=False),
    sa.Column('hair_color', sa.String(length=150), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=150), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    op.drop_table('character')
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('planets_gravity_key', type_='unique')
        batch_op.drop_constraint('planets_name_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_name_key', ['name'])
        batch_op.create_unique_constraint('planets_gravity_key', ['gravity'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('surface_water')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('terrain')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')

    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('homeworld', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='character_pkey'),
    sa.UniqueConstraint('homeworld', name='character_homeworld_key'),
    sa.UniqueConstraint('mass', name='character_mass_key'),
    sa.UniqueConstraint('name', name='character_name_key')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorite_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('fav_people')
    op.drop_table('people')
    op.drop_table('fav_planet')
    # ### end Alembic commands ###
